### PR TITLE
Spring support

### PR DESCRIPTION
**Pull request by ilndinesh**
I have added Spring context support. This is major change because the spring context is initialized on first run, and the way we get the resource objects has changed.

After this feature, we can write the rest services with spring annotation support, like autowiring etc.

### CODE REVIEW

**Comment by cagataygurturk** [comment]
Autowiring is really cool feature and I also had some work about that: https://github.com/cagataygurturk/aws-lambda-java-boilerplate

On the other hand I think this support should not be included in Lambada Framework but should be implemented by the user himself if he wants that.

There are alternative DI containers, for instance Guice and the user should be able to integrate it to his project, if he prefers it.

I think Lambada Framework's scope should be limited to JAX-RS implementation and HTTP handling.

**Comment by arranubels** [comment]
Could this be made a project which depends on Lambada? Such as:
https://github.com/lambadaframework/lambadaframework-with-spring?

**Comment by ilndinesh** [comment]
okay

**Comment by cagataygurturk** [comment]
This is an idea, @ilndinesh you can create a example project with Spring and we can mention about it at Readme file.

**Pull request closed without merging**
